export const SET_PRODUCT = 'SET_PRODUCT'
export const START_PRODUCT_FETCH = 'START_PRODUCT_FETCH'
export const STOP_PRODUCT_FETCH = 'STOP_PRODUCT_FETCH'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'